### ISSUE TITLE
Where does RL algorithm get initialized?

### ISSUE THREAD

**Issue by mansur007** [huawei-noah/SMARTS#1011]
**High Level Description**
In examples/rllib.py we can choose what RL algorithm to use by specifying the first argument of tune.run(...). 
If we want PPO we can run tune.run("PPO", ...).
I want to know some details of how PPO algorithm is initialized. For example, I want to see what distribution
is used for action sampling and how it is implemented.

Please help me find that place in code where the RL algorithm is initialized.
Thank you.

**Comment by Adaickalavan** [comment]
The code at `/SMARTS/examples/rllib` does not implement any reinforcement learning algorithms. The code merely uses RLlib's inbuilt algorithm implementations to train agents in SMARTS environment.

In order to learn how PPO is implemented, I would recommend looking at some code implementation examples such as https://keras.io/examples/rl/ppo_cartpole/ .

We hope the above addresses your question and thus this issue is being closed. Please feel free to reopen this issue if your problem persists or open a new issue for other questions.
