### ISSUE TITLE
Collision detection fails in NGSIM (history replacement)

### ISSUE THREAD

**Issue by zbzhu99** [huawei-noah/SMARTS#1137]
## **BUG REPORT**
**High Level Description**
When I run the imitation learning experiment in NGSIM environment, the off-road detection works fine but the collision detection (with other vehicles) does not work. 

**SMARTS version**
current master branch

**Steps to reproduce the bug**
Replace a history vehicle as a controlled ego vehicle in NGSIM dataset using similar code in examples/history_vehicles_replacement_for_imitation_learning.py and assign random action to that vehicle.

**Resulting and expected behaviour**
The controlled ego vehicle will not terminate even if it collides with other background vehicles.

**Error logs and screenshots**
<img width="655" alt="image" src="https://user-images.githubusercontent.com/32090492/143374098-f57ac9df-f57e-46b3-8e0f-f551a65e8455.png">

**Notes**
I uploaded the NGSIM scenario files I used here.
[NGSIM.zip](https://github.com/huawei-noah/SMARTS/files/7599962/NGSIM.zip)

**Comment by sah-huawei** [comment]
@zbzhu99:  Sorry I never found this problem for Issue #969. 

For what it's worth, I had three hypotheses at the time:

1. there might be a problem with the logic related to `dones` in `history_vehicles_replacement_for_imitation_learning.py` such that if there is more than one agent to be replaced in the sample (i.e., `k>1`), then the simulation will continue after the first agent collides because it thinks there are more to do.
2.  the problem might be related to the `pybullet` physics engine not using the vehicle chassis sizes specified in the history database.
3. the problem might be related to using a `BoxChassis` for the agent vehicle (which is deliberate here, but historically our agents have used `AckermannChassis`.

I had investigated (2) and (3) somewhat and, while I hadn't yet ruled them out, I was satisfied that if either of these was the problem, it wasn't straightforward.  I.e., they seemed on the surface to be doing the correct thing.

It was at this point that I got distracted by other work and never came back to this.  Sorry!

From what you wrote above, it appears we can probably rule out (1) as well because it seems you are only replacing one vehicle in this test.  (If that is not the case, please let us know though.)

I have written all this here so if someone else wants to investigate this too they might have a head start.

**Comment by CyberSY** [comment]
@sah-huawei :
I and @zbzhu99 have tested with single agent replacement and found the collision detection problem still existed.

**Comment by zbzhu99** [comment]
The problem has been resolved with PR #1143.
