### ISSUE TITLE
The return values of self._smarts.step(agent_actions) is empty dicts

### ISSUE THREAD

**Issue by zyk516** [huawei-noah/SMARTS#1271]
## **BUG REPORT**
**High Level Description**
I defined a training environments using RLlibHiwayEnv: env = RLlibHiWayEnv(config). 
When I ran env.step(action),  error happended:
assert (
            agent_actions.keys()
            == observations.keys()
            == rewards.keys()
            == infos.keys()
        )
raised an AssertionError.
I found observations, rewards, dones and extras that self._smarts.step(agent_actions) returned all were empty dicts.
I did not know  why this error happened and before this error my project could run for a period of time.And the observations that env.reset() returned was not empty.

**SMARTS version**
[e.g. 0.4.18]

**Error logs and screenshots**
WARNING:SMARTS:Attempted to perform actions on non-existing agent, hero 
Traceback (most recent call last):
  File "/home/idriver/zyk/study/rl/quick_done/train.py", line 178, in <module>
    main()
  File "/home/idriver/zyk/study/rl/quick_done/train.py", line 146, in main
    next_observations, rewards, dones, infos = env.step([accelate, brake, steering])
  File "/home/idriver/zyk/study/rl/quick_done/wrappers/smarts_env.py", line 104, in step
    env_observations, env_rewards, dones, infos = self.env.step(agent_actions)
  File "/home/idriver/zyk/study/rl/SMARTS-marl_benchmark_path_fixes/baselines/marl_benchmark/.venv/lib/python3.7/site-packages/smarts/env/rllib_hiway_env.py", line 151, in step
    == infos.keys()
AssertionError
 
**System information**
 
- Operating system & Environment [Please note if using Docker]:
- Python3.7
- SUMO1.5.0
Could someone tell me why?Thank you very much.

**Comment by Gamenot** [comment]
Hi @zyk516, is this line exact?

```
next_observations, rewards, dones, infos = env.step([accelate, brake, steering])
```

Normally `RLlibHiWayEnv.step` expects the action to be associated with an agent:

```
next_observations, rewards, dones, infos = env.step({"agent-007":[accelate, brake, steering]})
```

The signature of step looks roughly like this:
```
def step(self, actions: Dict[str, Any]) -> Tuple[
   Dict[str, Any],
   Dict[str, float],
   Dict[str, bool],
   Dict[str, Any]
]
```

**Comment by zyk516** [comment]
What I said is not very clear.
The variable env in next_observations, rewards, dones, infos = env.step([accelate, brake, steering]) is an instance of SmartsEnv that I defined.The class SmartsEnv has a member variable env: env = RLlibHiWayEnv(config).
SmartsEnv is defined as below:
class SmartsEnv(MultiAgentEnv):
    def __init__(self, config):
        self.env = RLlibHiWayEnv(config)

        self._agent_keys = list(config["agent_specs"].keys())
        self._last_observations = {k: None for k in self._agent_keys}
        self.num_stack = config['num_stack']
        self.frames = {
            agent_id: deque(maxlen=self.num_stack) for agent_id in self._agent_keys
        }
        self.frames_raw = {
            agent_id: deque(maxlen=self.num_stack) for agent_id in self._agent_keys
        }
        self.frames_rewards={
            agent_id: deque(maxlen=self.num_stack) for agent_id in self._agent_keys
        }
        one_frame_space = gym.spaces.Dict(
            goal_relative_pos=gym.spaces.Box(
                low=-float("inf"), high=float("inf"), shape=(2,)
            ),
            distance_to_center=gym.spaces.Box(
                low=-float("inf"), high=float("inf"), shape=(1,)
            ),
            speed=gym.spaces.Box(low=-float("inf"), high=float("inf"), shape=(1,)),
            steering=gym.spaces.Box(low=-float("inf"), high=float("inf"), shape=(1,)),
            neighbor=gym.spaces.Box(
                low=-float("inf"),
                high=float("inf"),
                shape=(8 * 5,),
            ),
            exist_lr_lane=gym.spaces.Box(low=0, high=1, shape=(4,))
        )
        self.observation_space = gym.spaces.Tuple([one_frame_space] * self.num_stack)
        self.feature_configs = {
            'goal_relative_pos': True,
            'distance_to_center': True,
            'speed': True,
            'steering': True,
            # 'heading_errors': [20, 'continuous'],
            'neighbor': 8,
            'exist_lr_lane':True
        }
        # self.info_adapter = None
        self.info_adapter = agent_info_adapter
    def step(self, agent_actions):
        agent_actions = {
            agent_id: agent_actions for agent_id in self._agent_keys
        }
        env_observations, env_rewards, dones, infos = self.env.step(agent_actions)
        for k, observation in env_observations.items():
            self.frames_raw[k].append(observation)
        rewards = self._get_rewards(env_rewards)
        infos = self._get_infos(env_observations, env_rewards, infos)
        return env_observations, rewards, dones, infos
The error happened in this line:
 env_observations, env_rewards, dones, infos = self.env.step(agent_actions).
When this error happened, the action is a dict{hero:[0.1499503429827076, 0, 0.012555409956576115]
}, and it is right.
I think this error is associated with this warning:
 WARNING:SMARTS:Attempted to perform actions on non-existing agent, hero.
Before steping the action, I reset the RLlibHiWayEnv and get right observations.But after that the agent disappear.
I do not know why.

**Comment by Gamenot** [comment]
@zyk516. Yes it would be related to `WARNING:SMARTS:Attempted to perform actions on non-existing agent, hero.` 

### Description
Up to very recently we managed the `dones` internally while fast forwarding the simulator to the first time the agent has observations which also used to be the first time an agent could also become `done`. That would cause some issues with the `gym.Env.reset()` and `rllib.MultiAgentEnv.reset()` interfaces which do not return `dones`. What would happen here is that a condition in `AgentInterface.done_criteria` is being met during `reset` by default that would be `off_road`, `collision`, or `off_route`(most likely `collision`.) Resetted environments that start this way are faulty since both.

### Suggestion
It is still possible to check for events in the `Observations.events` and match them up against the `AgentInterface.done_criteria`. If you check for the incompatibility in your implementation of `SmartsEnv.reset` you will be able to skip faulty environment configuration by resetting to a new scenario (and potentially log and prune faulty scenarios.)

This could look similar to the following:
```python
def reset(self, actions):
    
    attempts = 4
    for i in range(attempts):
        obs = self.env.reset(actions)
        success = True
        for agent_id, o in obs:
            events = o.events
            ### TODO: compare done critera and events
            # done_criteria = self.agent_specs[agent_id].interface.done_criteria
            ### For now just discard specific configurations that might be faulty
            assert not events.reached_max_episode_steps
            success = (
                not events.off_road
                and not events.reached_goal
                and len(events.collisions) == 0
                and not agents_alive_done
            )
            if not success:
                attempts -= 1
                self._log.warning(f"Reset failed due to agent: {agent_id}")
                break
        else:
            break
    else:
        raise RuntimeError("Could not successfully reset environment")

    return obs
```

### Further help
If you tell which version of `smarts` are you using (are you using 0.4.18?) I may be able to help a bit more.

If using develop there is a [recent push to `develop`](https://github.com/huawei-noah/SMARTS/commit/a44eb4e23eacdb3e5fe21ad72bc1a62668468685) which has changed the reset behaviour to partially help with the issue by requiring the agent to stay around until the first step at minimum. We have not yet figured out the fully correct approach because `AgentInterface` and the `Scenario` can be incompatible at runtime(e.g an scenario providing an actor from an off-road location for an agent with `AgentInterface.done_criteria.off_road == True`.)
