### ISSUE TITLE
Decrease CI time to run tests

### ISSUE THREAD

**Issue by JVillella** [huawei-noah/SMARTS#152]
It can be up to an hour (or worse: cancelled) to run the main tests. It should be less than 10 minutes, ideally only a few.

Move to Circle CI or pay GitHub.

**Comment by liamchzh** [comment]
Seems that using self-hosted runners is not supported yet (Hope they support this soon according to[ this reply](https://github.community/t/higher-cpu-count-virtual-environments-planned/16338))

A paid plan is not an option because we can't upgrade the machine. The [current specs](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources) of the runners are:
- 2-core CPU
- 7 GB of RAM memory
- 14 GB of SSD disk space

@Gamenot Consider moving to CircleCI?
