### ISSUE TITLE
Agent builder control multiple agents

### ISSUE THREAD

**Issue by yuant95** [huawei-noah/SMARTS#1721]
**Problems**
I'm exploring the agent interface feature in the smarts system. 

And I'm wondering whether there's anyway I could just have one custom agent builder that can control multiple agents? Like it can return actions of multiple agents at once given the observation, rather than only control one car at a time. This would be helpful for my simulation performance. 

Thanks in advance!

**Comment by Gamenot** [comment]
Hello @yuant95, we do have a concept that will allow for a single agent control multiple vehicles called a "boid" agent which can be generated generically for social agents but not ego agents.

## Social agents:
This can be seen in the "sumo/straight" scenario:

https://github.com/huawei-noah/SMARTS/blob/8823c603d26550c0a8b05283893ad198ff72b1e1/scenarios/sumo/straight/agent_prefabs.py#L59-L69

added to scenario here:

https://github.com/huawei-noah/SMARTS/blob/8823c603d26550c0a8b05283893ad198ff72b1e1/scenarios/sumo/straight/scenario.py#L6-L9

## Ego agents:
If you were trying the same thing from the example level it we originally had `AgentType.Boid` or `AgentInterface(ActionSpaceType.MultiTargetPose)` for this but it appears to be fairly indistinguishable from `TargetPose` at current because it only captures a single vehicle.

If you need this feature please make a request.

**Comment by yuant95** [comment]
Great, I only need it for the social agents. Thanks!
