### ISSUE TITLE
Add termination condition for the simulation

### ISSUE THREAD

**Issue by yuant95** [huawei-noah/SMARTS#1771]
**Problems**
I'm trying to set up the RL agent training with the simulator. Is there a way for me to add termination conditions for the episode? Right now my understanding is that one episode ends when the ego car crashes or exit the map. I'm having a bit hard time find out where in the code I can modify that? It would be great if anyone could point me to the right direction. Thanks!

**Comment by Gamenot** [comment]
Hello @yuant95, the episode generally concludes when all agents are done, there are options within the `AgentInterface` that help with that.

https://github.com/huawei-noah/SMARTS/blob/2d978eaf7fd48b618fe0fd2a5a03017cba9f3042/smarts/core/agent_interface.py#L239-L247

https://github.com/huawei-noah/SMARTS/blob/2d978eaf7fd48b618fe0fd2a5a03017cba9f3042/smarts/core/agent_interface.py#L206-L226

https://github.com/huawei-noah/SMARTS/blob/2d978eaf7fd48b618fe0fd2a5a03017cba9f3042/smarts/core/agent_interface.py#L196-L202

The agent interface fits on the agent spec as shown here in the documentation: https://github.com/huawei-noah/SMARTS/blob/master/docs/sim/agent.rst#how-to-build-an-agent

Otherwise, termination of an episode should be possible from the outside by forcing an early reset.
