### ISSUE TITLE
Is the steering angle in an ActuatorDynamic action space degrees or radians?

### ISSUE THREAD

**Issue by ajlangley** [huawei-noah/SMARTS#1833]
**High Level Description**
As title. I just couldn't find the steering angle units.

**Desired SMARTS version**
1.0.1

**Comment by Gamenot** [comment]
@ajlangley The units should always be in SI aside from the action. The following should roughly be the case:

`action` for `ActuatorDynamic` is a clipped value between `[-1, 1]` (clipped_steering_change).
`p` is a constant `1 - 1e-3`.
`dt_sec` is the time-step in seconds (typically 0.1s)

ActuatorDynamic modifies the action in the following way:
`steering_control = p * last_steering_control + clipped_steering_change * dt_sec`

For our typical vehicle, the steering wheel we model has 2 radians (max_steering) of turn and a steering gear ratio of 17.4 (steering_gear_ratio).

Both wheels use the following equation:
`-steering_control * max_steering * (1/steering_gear_ratio)`

**Comment by ajlangley** [comment]
Thanks for your reply. In that case, if I added ActuatorDynamics to the FormatAction environment wrapper and set the action space to Box([-1, 1], [-1, 1], [-2*pi, 2.pi]), would that be of interest?

**Comment by Gamenot** [comment]
Hello, @ajlangley. My understanding is that [ActuatorDynamic](https://smarts.readthedocs.io/en/latest/api/smarts.core.controllers.html#smarts.core.controllers.ActionSpaceType.ActuatorDynamic) uses the same `Box([0, 1], [0, 1], [-1, 1])` as [Continuous](https://smarts.readthedocs.io/en/latest/api/smarts.core.controllers.html#smarts.core.controllers.ActionSpaceType.Continuous).

I am surprised reading the documentation that we did not make this properly noted. I am updating the current documentation to make this clear.

Otherwise, this is still of interest.

**Comment by ajlangley** [comment]
Great, thanks for the quick response.
