### ISSUE TITLE
ModuleNotFoundError in 'examples', but I soved that.

### ISSUE THREAD

**Issue by Fleming-Sung** [huawei-noah/SMARTS#1837]
## **BUG REPORT**
Traceback (most recent call last):
  File "examples/control/chase_via_points.py", line 12, in <module>
    from tools.argument_parser import default_argument_parser
ModuleNotFoundError: No module named 'tools.argument_parser'

**SMARTS version**
1.0.3

**Steps to reproduce the bug**
Add __init__.py file in the lost package's direct, e.g. 'examples/tools/__init__.py' for this specific error info.
The __init__.py file can be empty.

**Resulting and expected behaviour**
SOLVED!
Suggest to check and repair all the sub-packages.
 
**System information**
- Operating system & Environment [Please note if using Docker]:Ubuntu18.0.04
- Python version [Please note if using Jupyter]:3.8(anaconda)

**Comment by Gamenot** [comment]
@Fleming-Sung Thank you for the report, we have a slightly different fix proposed that adds the SMARTS repository to the path in #1825.

I think your proposed solution may also work since it makes the imports easy to maintain. I am still a little cautious about adding `__init__.py` because it will add an `examples` into the importable modules for all python programs running from the SMARTS repository directory. We wish to avoid unintentional behaviour.


We will discuss which option makes most sense.

**Comment by Gamenot** [comment]
We have decided to go with the approach in #1825. If it turns out to not enough we will add `__init__.py` and exclude the directory from the `wheel` build.
