### ISSUE TITLE
Envision won't render custom scenario

### ISSUE THREAD

**Issue by ajlangley** [huawei-noah/SMARTS#1874]
**High Level Description**
I have made a custom road network using SUMO. The issue is that Envision won't render the scenario (the whole browser window goes black the instant an ego vehicle enters the scene).

**Desired SMARTS version**
1.0.3

**Operating System**
Ubuntu 20.04

**Problems**
I have the following custom road network. In `map.nod.xml`, I have
```
<?xml version="1.0" encoding="UTF-8"?>

<nodes>
    <node id="J0" x="0.0" y="0.0" />
    <node id="J1" x="20.0" y="0.0" />
    <node id="J2" x="30.0" y="0.0" />
    <node id="J3" x="40.0" y="0.0" />
    <node id="J4" x="60.0" y="0.0" />
    <node id="J5" x="30.0" y="10.0" />
    <node id="J6" x="30.0" y="30.0" />
    <node id="J7" x="30.0" y="-10.0" />
    <node id="J8" x="30.0" y="-30.0" />
</nodes>
```
and in `map.edg.xml` I have

```
<?xml version="1.0" encoding="UTF-8"?>

<edges>
    <edge from="J0" to="J1" id="0to1" />
    <edge from="J1" to="J0" id="1to0" />
    <edge from="J1" to="J2" id="1to2" />
    <edge from="J2" to="J1" id="2to1" />
    <edge from="J2" to="J3" id="2to3" />
    <edge from="J3" to="J2" id="3to2" />
    <edge from="J3" to="J4" id="3to4" />
    <edge from="J4" to="J3" id="4to3" />
    <edge from="J2" to="J5" id="2to5" />
    <edge from="J5" to="J2" id="5to2" />
    <edge from="J5" to="J6" id="5to6" />
    <edge from ="J6" to="J5" id="6to5" />
    <edge from="J2" to="J7" id="2to7" />
    <edge from="J7" to="J2" id="7to2" />
    <edge from="J7" to="J8" id="7to8" />
    <edge from="J
8" to="J7" id="8to7" />
</edges>
```
I built the map file, `map.net.xml` using the command
```netconvert --node-files=hello.nod.xml --edge-files=hello.edg.xml --output-file=map.net.xml```
Finally, in my scenario file, `scenario.py`, I have
```
from pathlib import Path

from smarts.core import seed
from smarts.sstudio.genscenario import gen_scenario
import smarts.sstudio.types as t

routes = [
    t.Route(begin=('0to1', 0, 'random'), end=('2to3', 0, 'random'))
]
ego_missions = [t.Mission(route=route) for route in routes]

gen_scenario(
    scenario=t.Scenario(
        ego_missions=ego_missions),
    output_dir=Path(__file__).parent
)
```
Now, when I run Envision and attempt to visualize this scenario with a single ego vehicle, the road network pops up, but then the entire browser window (everything under the search bar) goes completely black as soon as the vehicle enters the scene. This has something to do with the choice of mission, as when I replace the route with
```t.Route(begin=('1to2', 0, 'random'),end=('2to3', 0, 'random')```
it renders as expected. Basically, the only missions is will render are 
1to2 -> 2to3
3to2 -> 2to1
5to2 -> 2to7
7to2 -> 2to5

Is there any idea what's going on?

P.S.: Thanks for all of the assistance recently.

**Comment by Gamenot** [comment]
Thank you for the question @ajlangley I am going to try this out to see what might be wrong.

**Comment by Gamenot** [comment]
## Error
The browser console notes the following issue:

```txt
Uncaught TypeError: Cannot read properties of undefined (reading 'equalsWithEpsilon')
    at Function.PolygonBuilder.CreatePolygon (polygonBuilder.js:116)
    at Function.MeshBuilder.CreatePolygon (meshBuilder.js:456)
    at mission_routes.js:64
    at Array.forEach (<anonymous>)
    at _loop (mission_routes.js:62)
    at mission_routes.js:61
    at commitHookEffectListMount (react-dom.development.js:19731)
    at commitPassiveHookEffects (react-dom.development.js:19769)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
```

## mission_routes.js:64
https://github.com/huawei-noah/SMARTS/blob/c2edd5d9c83350de5effbe5eb022798def3e4380/envision/web/src/components/mission_routes.js#L64-L68

From that I note that somehow an empty array managed to make it into `missionRoutes` through `mission_route_geometry`.

![image](https://user-images.githubusercontent.com/8764693/219905167-908983f4-8a89-4766-9520-e3862253884f.png)

And appears to come from:
https://github.com/huawei-noah/SMARTS/blob/c2edd5d9c83350de5effbe5eb022798def3e4380/smarts/core/smarts.py#L1508-L1515

It looks like one of the lanes generated is unexpectedly 0 length and thus would not have any geometry:
```python
<smarts.core.sumo_road_network.SumoRoadNetwork.Road object at 0x7ff192c76fa0>
(Pdb) route.roads[1].lanes
[<smarts.core.sumo_road_network.SumoRoadNetwork.Lane object at 0x7ff192c76f70>]
(Pdb) route.roads[1].lanes[0].lane_id
':J1_1_0'
(Pdb) route.roads[1].lanes[0].length
0.0
```

The generated file gives the lane which means the conversion is somehow reducing the length of the lane. It is not large enough to be decimal error but enough that inaccuracy could cause it.
```map.net.xml
    <edge id=":J1_1" function="internal">
        <lane id=":J1_1_0" index="0" speed="13.89" length="0.10" shape="20.00,28.40 20.00,28.40"/>
    </edge>
```

Checking SUMO for underlying problems it appears that SUMO caused the issue because the sumo shape does not match the length both above and below:
```python
(Pdb) route.roads[1].lanes[0].lane_id
':J1_1_0'
(Pdb) route.roads[1].lanes[0].length
0.0
(Pdb) route.roads[1].lanes[0]._sumo_lane.getShape()
[(20.0, 28.4), (20.0, 28.4)]
(Pdb) route.roads[1].lanes[0]._sumo_lane.getLength()
0.1
```

It may be a rounding error within SUMO's shape generation.

I think this behavior can be filed as an issue against the SUMO repository.

**Comment by Gamenot** [comment]
I will have to think about what should be done about this issue. We did not anticipate 0 length lanes.

**Comment by Gamenot** [comment]
I have applied a fix.

**Comment by ajlangley** [comment]
Thank you for the help!
