### ISSUE TITLE
Malformed waypoints for agents using Mission and EndlessMission in Argoverse maps

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#1926]
After PR #1923, some waypoints appear malformed in Argoverse maps. 

Waypoints appear malformed differently in agents using "Mission" compared to agents using "EndlessMission". Preferably, agents using "Mission" and "EndlessMission" should generate waypoints in the same manner, with the exception of agents using "EndlessMission" should get all legal waypoints at each time point whereas agents using "Mission" should only get the waypoints leading to the goal at each time point.  

A sequence of images showing malformed (i) social agent waypoints using "Mission" and (ii) ego agent waypoints using "EndlessMission", is shown below in Argoverse map `c624608b-fd20-43c9-bc2c-c4181ce9dafa`.

1) Social agent waypoints in the current lane stops abruptly and does not branch to the south, but ego agent waypoints does branch to the south.
    <img src="https://user-images.githubusercontent.com/24203326/227794042-e124f91a-4555-4e4d-89af-8c1bd15024c9.png" width=500px height=500px>
    <img src="https://user-images.githubusercontent.com/24203326/227795581-e83a757b-b1e9-4d33-a110-4a7ee9ade215.png" width=500px height=500px>

2) Social agent waypoints depict a wierd shape like "7" in the intersection.
    <img src="https://user-images.githubusercontent.com/24203326/227795468-318f6418-082e-4601-8c8b-96423d14e90a.png" width=500px height=500px>

3) Ego agent waypoints pointing straight ahead in the current lane disappears and instead waypoints pointing to a left-turn appears. This happens for exactly one time step, after which the left-turn waypoints disappears and the waypoints pointing straight ahead reappears. Two consecutive images are shown below depicting this phenomenon. The embedded rgb images, in each image below, show three consecutive time points.  
    <img src="https://user-images.githubusercontent.com/24203326/227795715-64aeacc8-63dc-4b21-baad-99113f697cd8.png" width=800px height=400px>
     <img src="https://user-images.githubusercontent.com/24203326/227795716-97ac289e-65db-4792-aeae-593472f006c4.png" width=800px height=400px>

**Comment by saulfield** [comment]
For the first issue of the social agent with a `Mission`, the waypoints/route generation are actually "correct", but they look a bit strange because of the road structure. See the below image:

![image](https://user-images.githubusercontent.com/17256344/228032526-947ace04-c5ae-4058-a39b-4b108e29534a.png)

Road 1 branches off into roads 2 & 3, which each connect into road 4, which has 2 lanes. The route planner has to pick a single path, so goes with road 2. It then generates waypoints on road 4 connecting to the correct exit lane to reach the goal in the southbound road. The "7" shape is a consequence of driving straight through the intersection instead of following the waypoints to the south.

The key thing here is that waypoints for missions are tied to a path of roads leading from the start to the end, so you should not expect it to generate waypoints for all possible paths (like the ego here). If you want to constrain the path to use certain roads, you can add via points.

We could think about supporting multiple routes in the pathfinder, but that would be another issue.

**Comment by Adaickalavan** [comment]
Everything remains the same and up to date with the current `master` branch. The only exception being the contents of the file `smarts/core/argoverse_map.py` was reverted to that prior to PR #1923. We then get the following which is what one would normally expect. The result appears to be [different](https://github.com/huawei-noah/SMARTS/issues/1926#issue-1641025437) after PR #1923. 

![Screenshot from 2023-03-27 15-10-06](https://user-images.githubusercontent.com/24203326/228043192-b7c2be0e-48fa-4dea-b382-c4be9cbe5734.png)

**Comment by saulfield** [comment]
Yes, this is because previously road 4 would be split up into 2 separate roads. This constrains the route to be made up of 1-lane roads, which looks more "correct" in this case, but is just a result of less options for the path. The change is necessary to correctly infer roads of multiple lanes. Routefinding and traffic flows would not behave correctly without it. If you need the route to take that specific path, you can use via points in the mission.
