### ISSUE TITLE
Scenario issues

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#2004]
### High Level Description

This is on the `merge_exit` map. Expected waypoints to behave like that shown [here](https://smarts.readthedocs.io/en/latest/_images/merge-single.gif). But got the below issues in chronological order:
+ In on-ramp, agent sees three waypoint paths. [ok]
+ In on ramp, three waypoint paths extends across the junction. [ok] 
+ In junction, agent sees single waypoint path which jumps around. [probably scenario issue]
+ After merge in highway, waypoint paths end abruptly. [probably scenario issue]
+ In highway, three short and thick lines appear. [probably scenario issue]
+ In highway, at the very end of the gif, `obs.waypoint_paths` is empty, causing the episode to crash. [probabaly scenario issue]

![Peek 2023-04-28 19-40](https://user-images.githubusercontent.com/24203326/235272307-0aee1160-3187-4206-b867-e5d9790176a1.gif)

### Version

branch: master
version: v1.0.11

### Steps to reproduce the bug

```shell
Replay the `merge_exit` scenario and visualize the waypoints.
```

### Impact (If known)

The `merge_exit` scenario is unusable.

**Comment by qianyi-sun** [comment]
@Adaickalavan The issues are mostly due to overlapped edges around the junctions, if the edges are overlapped, the waypoints are overlapped as well, which leads to:
- confusion on picking the right waypoints path (jump around issue)
- dense, crowded waypoints in a small edge (three thick lines) 

To fix this, 
- modified the geometry endpoints for most of the edges to minimize the overlapping around the junction so that the waypoints are generally clearer and smoother.
- extend edges/junctions a bit for same reason above, and also can give more room/time to access the upcoming waypoints in the observations

Please take a look at the following gif and let me know if this is acceptable, I have already pushed this map onto the repo, thanks!

![merge_fix](https://user-images.githubusercontent.com/59240680/235287603-355b5eac-ec52-4497-8915-873c496554d4.gif)

**Comment by Adaickalavan** [comment]
More scenario issues on straight map.

![straight](https://user-images.githubusercontent.com/24203326/235307213-07656be2-885a-40d3-842c-280b1fd7732f.gif)
![Peek 2023-04-28 22-15](https://user-images.githubusercontent.com/24203326/235307222-1c4a324c-110c-4c99-a54b-3d6573d33963.gif)

+ Use entry tactic method to ensure lead vehicle appears before ego, rather than map design methods.
+ Check and rectify **all** scenarios for similar issues.

**Comment by Adaickalavan** [comment]
The modified `merge_exit` map seems to use junctions with lane-change connections to specify the locations where the lead vehicle could change lane, albeit the decision to change lane is random. Since the above [gif](https://user-images.githubusercontent.com/59240680/235287603-355b5eac-ec52-4497-8915-873c496554d4.gif) uses an EndlessMission agent, the same set of waypoints will be seen by the ego agent. Essentially, the modified maps reveal a degree of privileged info to the ego on where potential lane changes by the lead vehicle could happen, in contrary to the idea of the task where ego should not have any prior knowledge of the leader's trajectory.  

![Screenshot from 2023-04-29 10-33-11](https://user-images.githubusercontent.com/24203326/235309066-f163e8e0-7e0b-4017-bed2-6ecc39fce755.png)

![Screenshot from 2023-04-29 10-51-50](https://user-images.githubusercontent.com/24203326/235309060-5c56c5bd-e355-4897-b498-015d945b59a1.png)

**Comment by qianyi-sun** [comment]
> More scenario issues on straight map.
> 
> ![straight](https://user-images.githubusercontent.com/24203326/235307213-07656be2-885a-40d3-842c-280b1fd7732f.gif) [ ![straight](https://user-images.githubusercontent.com/24203326/235307213-07656be2-885a-40d3-842c-280b1fd7732f.gif) ](https://user-images.githubusercontent.com/24203326/235307213-07656be2-885a-40d3-842c-280b1fd7732f.gif) [ ](https://user-images.githubusercontent.com/24203326/235307213-07656be2-885a-40d3-842c-280b1fd7732f.gif) ![Peek 2023-04-28 22-15](https://user-images.githubusercontent.com/24203326/235307222-1c4a324c-110c-4c99-a54b-3d6573d33963.gif) [ ![Peek 2023-04-28 22-15](https://user-images.githubusercontent.com/24203326/235307222-1c4a324c-110c-4c99-a54b-3d6573d33963.gif) ](https://user-images.githubusercontent.com/24203326/235307222-1c4a324c-110c-4c99-a54b-3d6573d33963.gif) [ ](https://user-images.githubusercontent.com/24203326/235307222-1c4a324c-110c-4c99-a54b-3d6573d33963.gif)
> 
> * Use entry tactic method to ensure lead vehicle appears before ego, rather than map design methods.
> * Check and rectify **all** scenarios for similar issues.

We haven implemented such entry tactic yet, i believe it's in progress on PR#1965.

**Comment by Adaickalavan** [comment]
On the modified `merge_exit` map, we see the following:
+ The lead vehicle waits too long at the merge such that the episode terminates due to reaching `max_steps_per_episode`.
+ The background traffic seems to always change lane to left-most lane prior to the merge location. This severely reduces any traffic interaction this scenario presents to the ego.
+ Background traffic vehicles and lead vehicle seems to akwardly gain speed between the newly introduced consecutive lane-change junctions in the main road.

![Peek 2023-04-29 11-43](https://user-images.githubusercontent.com/24203326/235311568-b537adb9-c2be-4197-8de0-f9d95f3d7dbf.gif)

**Comment by qianyi-sun** [comment]
> On the modified `merge_exit` map, we see the following:
> 
> * The lead vehicle waits too long at the merge such that the episode terminates due to reaching `max_steps_per_episode`.
> * The background traffic seems to always change lane to left-most lane prior to the merge location. This severely reduces any traffic interaction this scenario presents to the ego.
> * Background traffic vehicles and lead vehicle seems to akwardly gain speed between the newly introduced consecutive lane-change junctions in the main road.
> 
> ![Peek 2023-04-29 11-43](https://user-images.githubusercontent.com/24203326/235311568-b537adb9-c2be-4197-8de0-f9d95f3d7dbf.gif) [ ![Peek 2023-04-29 11-43](https://user-images.githubusercontent.com/24203326/235311568-b537adb9-c2be-4197-8de0-f9d95f3d7dbf.gif) ](https://user-images.githubusercontent.com/24203326/235311568-b537adb9-c2be-4197-8de0-f9d95f3d7dbf.gif) [ ](https://user-images.githubusercontent.com/24203326/235311568-b537adb9-c2be-4197-8de0-f9d95f3d7dbf.gif)

- re 1): There can be two possible solution: 1) reduce the traffic density 2) give the on-ramp higher road priority, which would lead to all traffic vehicle stops at the intersection when the leader is merging in. 3) put a traffic light on that junction.

Please let me know which one is prefered, imp, it depends on how we see this scenario as, if we see this as a hiway scenario, then reducing density might be appropriate. if it's just a urban road with some merging junctions, we might want to add traffic light or modify the road right priority instead.
- re 2): I dont see this happens on my end, it's pretty random as shown below
- re 3): I reported this to @Gamenot already, we checked every speed config/info in those files, the cause is unknown and might be a sumo issue.

![merge_traffic](https://user-images.githubusercontent.com/59240680/235312540-9b368fc2-7ac5-4449-867a-11a8dafbc532.gif)

**Comment by qianyi-sun** [comment]
I have pushed several map changes and tested them, please take a look and let me know if any more change is required, thanks @Adaickalavan !

**Comment by qianyi-sun** [comment]
I reduced the traffic density a bit, the current traffic looks reasonable to me and doesnt block the leader to merge in
