### ISSUE TITLE
[Help Request] About the version of ray

### ISSUE THREAD

**Issue by ClorisUcas** [huawei-noah/SMARTS#2047]
**Error:**
(raylet)   File "/home/k/Desktop/SMARTS-1.1.0/.venv/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 20, in <module>
(raylet)     import aiohttp.signals
(raylet) ModuleNotFoundError: No module named 'aiohttp.signals'

**Question**
Hi folks,
I am trying to run baselines/marl_benchmark/run.py, but some errors happens.
I find it's because of the version of aiohttp(3.8.4) is not suitable for Ray(1.4.0), but when I try to modify the version of aiohttp or ray, other dependency problems happen.
I really appreciate if you can help me^^

**Comment by Gamenot** [comment]
Hello @ClorisUcas, we have moved `MARL` out of the repository recently since we are not actively up-keeping it for the current version of SMARTS. The main issue has been that the dependencies have become problematic to maintain.

As to how the situation currently stands, a fix of the dependencies will require us to upgrade RLlib to a modern version.

Considering this has been desirable since https://github.com/huawei-noah/SMARTS/issues/1238 I will try this over the weekend. I can get back to you by Monday on it.

**Comment by Gamenot** [comment]
I apologize, I have been unable to work through this as early as I expected.

**Comment by ClorisUcas** [comment]
It’s ok. Thank you for your hard working and  kind reply.
I also tried a lot of methods to solve it, but it's a difficult problem.
Now based on your single agent work, I am trying to finish multi-agent with other RL library.
