### ISSUE TITLE
[Help Request] Does Any Non-False Event Indicate the End of an Episode (done=True)?

### ISSUE THREAD

**Issue by l1xiao** [huawei-noah/SMARTS#2095]
### High Level Description

Hello,

I was wondering if any event being not False indicates that the variable 'done' is set to True, signifying the end of the current episode? I've looked through the documentation but couldn't find a clear answer.ref：https://smarts.readthedocs.io/en/latest/api/smarts.core.events.html#smarts.core.events.Events

Could you please help clarify this for me?
Thank you for your time and assistance.

### Version

1.4.0

**Comment by Gamenot** [comment]
Hello, thank you for the question.

The event docstring does not confirm this because it only contributes. If any of events resolves true it indicates that the agent may be "done" if the agent interface also declares through the "done_criteria" that the given event should cause the agent to be done.

https://smarts.readthedocs.io/en/latest/api/smarts.core.agent_interface.html#smarts.core.agent_interface.DoneCriteria
