### ISSUE TITLE
[Help Request] Convert observations into tensors

### ISSUE THREAD

**Issue by knightcalvert** [huawei-noah/SMARTS#2098]
### High Level Description

my simplified observations looks like:
```
({
    'Agent 0': {'active': 1, 'steps_completed': 1, Waypoint(pos=array([134.8,43.03544217]), heading=Heading(0.0)}, 
    'Agent 1': {'active': 1, 'steps_completed': 1}
},
{
    'Agent 0': {'score': 0, 'env_obs': 0, 'done': False, 'reward': 0, }, 
    'Agent 1': {'score': 0, 'env_obs': 0, 'done': False, 'reward': 0, }
})
```

### Version

1.4.0

### Problems

i can't convert this obs into tensors`tensor = th.tensor(obs, dtype=dtype, device=self.device)`, i'm so confused about what type the waypoint or via etc. is, could someone give me a simple example about `def get_obs(self):` and `def get_state(self):` thank you for your reply

**Comment by Adaickalavan** [comment]
Hi @knightcalvert,

Observation for each individual agent is a dictionary with multiple key value pairs. Refer [here](https://smarts.readthedocs.io/en/latest/api/smarts.core.observations.html#smarts.core.observations.Observation) and [here](https://smarts.readthedocs.io/en/latest/api/smarts.env.utils.observation_conversion.html#smarts.env.utils.observation_conversion.ObservationSpacesFormatter), which describes the observation structure and the formatted observation.

We should cast the desired individual components of the observation to tensors, rather than casting the entire observation into a tensor.

If you need further clarification, providing a minimal working code along with the question, will enable us to provide more specific assistance.
