### ISSUE TITLE
Path from start point to end point flows in the opposite direction of the generated route

### ISSUE THREAD

**Issue by n00b-c0dr** [huawei-noah/SMARTS#2107]
### High Level Description

I am using SMARTS to train a PPO Model (using sb3), and I have created a script that uses the benchmark metrics to evaluate my model every few thousand time steps of training.
I am using functions from _smarts/env/gymnasium/wrappers/metric/_ to evaluate my trained model.
I am facing the same error on multiple scenarios in _sumo/intersection/_ 

### Version

v 1.1.0

### Operating System

Ubuntu 18.04.6

### Problems

After a few epochs of alternating training and evaluation, I face an error while one the evaluation loops is running.

**Comment by n00b-c0dr** [comment]
Can someone please guide me on what could be the cause of this error?

**Comment by Adaickalavan** [comment]
Hi @n00b-c0dr,

1. Please ensure that you are using the latest code version from the master branch, as I am unable to find the function `_get_dist` on line 570 in file `SMARTS/smarts/env/gymnasium/wrappers/metric/costs.py`. The error message appears to be from an older code version.

1. To efficiently debug this, please provide a minimum working example to reproduce the error.

1. In general, this type of error is thrown when distance computation on the underlying map file fails. The [Metrics](https://github.com/huawei-noah/SMARTS/blob/aea2056ed3b411af04c80b9d44f1c61493622c21/smarts/env/gymnasium/wrappers/metric/metrics.py#L436) has been tested to work on all training scenarios listed in [Driving SMARTS 2023.1 & 2023.2](https://smarts.readthedocs.io/en/latest/benchmarks/driving_smarts_2023_1.html#training-scenarios) and [Driving SMARTS 2023.3](https://smarts.readthedocs.io/en/latest/benchmarks/driving_smarts_2023_3.html#training-scenarios).

1. Please paste any error messages in text format, instead of image format, to help us easily search for the errors.

**Comment by n00b-c0dr** [comment]
Thank you for your reply. Sorry for pasting the error screenshot, I'll keep in mind the correct format.
We have been building our project using SMARTS v1.1.0 for a while now and it never gave that error until now. We prefer to stick to that version as it will require us to change our whole code if  we change the SMARTS version. 
I will look into the points you mentioned and if required, I will reopen the issue for further help.
