### ISSUE TITLE
[Help Request] Other interaction dataset maps

### ISSUE THREAD

**Issue by ShenZC25** [huawei-noah/SMARTS#2115]
### High Level Description

scenarios help about INTERACTION Dataset

### Version

1.4.0

### Operating System

win11

### Problems

Dear developers, hello, thank you for your excellent work.

I see that our simulation platform supports the simulation of INTERACTION Dataset, but it seems that there is only Merging scene. Then, I may need all the scenes of this data set. Could you please add relevant scenes? If not, can you tell me how to do it? Because it may involve the coordinate alignment of the map and other issues. (For example, its map in lanelet2 format seems to be osm's, so it can't be directly converted by using SUMO's neteit, and it needs to be drawn manually. Hope to complete the relevant map)

Thank you

**Comment by Gamenot** [comment]
Hello @ShenZC25, whenever I have had to do the conversion I have attempted to use the CommonRoad utilities to make the conversion:

Either through the GUI directly https://gitlab.lrz.de/tum-cps/commonroad-scenario-designer/-/blob/main/README.md or using the methods within the package https://pypi.org/project/commonroad-scenario-designer/

Do note that it is a lossey conversion because it has to go through the CommonRoad format intermediary.
