### ISSUE TITLE
[Help Request] Need to customize vehicle parameters

### ISSUE THREAD

**Issue by Frzgunr1** [huawei-noah/SMARTS#2116]
### High Level Description

    I need to customize the parameters of the vehicle for my research using SMARTS, for example, I want to create a truck with a different crashbox than a normal vehicle and I want it to have a different color in the visualization.
     Which files do I need to modify in this case?
      Looking forward to your help, I will cite SMARTS in my paper. thank you very much!

### Version

ver [1.4.0]

### Operating System

ubuntu 20.04

**Comment by Gamenot** [comment]
Hello @Frzgunr1, I will look into this tomorrow to see what work would be involved.

Do you have a specific model of truck you are looking for? The main resource requirement is a `urdf` file of the vehicle you want.

**Comment by Gamenot** [comment]
Hello @Frzgunr1, what is given in #767 is unfortunately just a set of visual models, it is still missing the dynamics model.

The two current physics models are hardcoded in `vehicle.py` to draw from `smarts/core/models/` one of `vehicle.urdf` (`"sedan"`) or `bus.urdf` (`"bus"`) based on the value of `AgentInterface.vehicle_type`.

# Question

What is your timeline?

**Comment by Gamenot** [comment]
## Investigation

There are a few components to a vehicle within our simulation.
- Visuals
- Physics model
- Controller model
- Selection

### Selection (via AgentInterface)
Current vehicle selection is done in the agent interface:
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/agent_interface.py#L323-L326

And constrained:
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/agent_interface.py#L370

This currently is resolved to a `urdf` when the vehicle is constructed:
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/vehicle.py#L300-L305

### Visuals
The vehicle state is where the visual representation of the vehicle is resolved and where the simulation is intended to redirect to the appropriate `.glb`.
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/vehicle_state.py#L50-L93

It also looks like there is currently a bug that does not forward the visual vehicle configuration and default dimensions when generating agents:
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/vehicle.py#L339-L343

This would normally be done through specifying `vehicle_config_type` (relating to `VEHICLE_CONFIGS`).
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/vehicle.py#L58-L70

### Physics
The physics is represented in the following way:

#### Bus
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/models/bus.urdf#L1-L135
#### Sedan
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/models/vehicle.urdf#L1-L135

There appears to be a second bug related to vehicle selection in which the vehicle can only ever have the dimensions of the default `"passenger"` vehicle instead of using information from the `AgentInterface.vehicle_type`.
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/vehicle.py#L286
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/vehicle.py#L248-L266

### Controller
The controller arguments are currently defined here:
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/models/controller_parameters.yaml#L1-L51

It looks like there is a final bug where if a vehicle is replaced (rather than a new vehicle generated) the `"sedan"` no configuration is used:
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/vehicle_index.py#L462

https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/chassis.py#L328-L342

https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/chassis.py#L52-L57

Configuration is intended to be provided such as with a newly generated vehicle:
https://github.com/huawei-noah/SMARTS/blob/c2ebaaaca4eec8d122f7c75143b899b1611095c9/smarts/core/vehicle.py#L322-L330

## 
- I will do a fix of the 3 bugs that I noted above tomorrow.
- I will patch in the remaining vehicle configuration options (particularly the truck configuration) but you will need to modify some things as you need.
  - You would need to acquire a truck `urdf`
  - You would need to tune the controller
- I will expand the colour configuration in the scenario to also affect agents.
- I am unable to get to a broader vehicle configuration interface until the middle of next month.
- I am unable to do controller tuning until later next month.

**Comment by Gamenot** [comment]
# Result
- I will do a fix of the 3 bugs that I noted above tomorrow.
- I will patch in the remaining vehicle configuration options (particularly the truck configuration) but you will need to modify some things as you need.
  - You would need to acquire a truck `urdf`
  - You would need to tune the controller
- I will expand the colour configuration in the scenario to also affect agents.
- I am unable to get to a broader vehicle configuration interface until the middle of next month.
- I am unable to do controller tuning until later next month.

**Comment by Gamenot** [comment]
@Frzgunr1 I am about to start work on this, is there a particular grade of truck you are looking for?

- Large pickup truck (e.g. Ford F150, Toyota Tacoma)
- Small semi-trailer (e.g. Toyota Dyna)
- Large semi-trailer (e.g. Mack, Kenworth, Mercedes FAW)
- Integrated (e.g. garbage truck, fire engine, ambulance)

**Comment by Frzgunr1** [comment]
Sure,just use the [truck (7.1m) as is defined by SUMO](https://sumo.dlr.de/docs/Vehicle_Type_Parameter_Defaults.html). 
   Then We could make more customized vehicles！
