### ISSUE TITLE
Goal-condition/mission of social/hijacked agents

### ISSUE THREAD

**Issue by Nickniyihan** [huawei-noah/SMARTS#257]
- Does hijacked bubble agents have mission or goal of each vehicle like social_agent_mission?
- Does individual sumo vehicle have mission or goal that expose to user? What's the relationship with traffic definition?
- How does sumo vehicle redefine a goal or mission when the vehicle is moved out of original planned path?

A potential feature request: To expose goal condition or mission through social agent API, aka. policy observation.

AC:
- [x] Answer @Nickniyihan 's questions
- [x] Spin out goal condition feature request

**Comment by Gamenot** [comment]
@Nickniyihan Answers to questions are as follows:

> * Does hijacked bubble agents have mission or goal of each vehicle like social_agent_mission?

Currently the social agent constructed by the bubble gets a mission plan that defaults to a goal halfway on the last edge of the route that the traffic vehicle had.

> * Does individual sumo vehicle have mission or goal that expose to user? What's the relationship with traffic definition?

 If you have access to the traffic sim you are able to get the goal of the SUMO vehicle, however that should generally not be the case. So the current exposed interface for it is only through scenario studio (sstudio.) The traffic currently formats in the following way: 

https://github.com/huawei-noah/SMARTS/blob/8881e07ad83aea83e1b02d98a1bf65d851a3e392/smarts/sstudio/generators.py#L228-L243

with the definition of terms here:
https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html

Currently the sstudio API is very heavily influenced by the sumo `net.xml` traffic and flow specifications.

> * How does sumo vehicle redefine a goal or mission when the vehicle is moved out of original planned path?

SUMO can take a number of actions depending on the setting. As applies to us SUMO can try to take one of two actions: if the original destination is available it may reroute to reach that destination, otherwise it attempts to remove the vehicle. We override by giving a new mission if there is no way to route to its destination.

**Comment by Gamenot** [comment]
Spun out issue #419.
