### ISSUE TITLE
Address Floating Point Error in Envision Visualization

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#325]
Maps that are located at extreme distances from 0 can cause geometry distortion in envision.

![BadVisualLaneChangeInIntersection](https://user-images.githubusercontent.com/8764693/102424806-f96c2780-3fd9-11eb-8110-b24142d2bdf9.gif)

AC:
- [ ] A map located at 3e8 shows vehicles without distortion in envision.

**Comment by liamchzh** [comment]
The maps are in #312, just choose it, such as `relative_0_speed_30km`

**Comment by Gamenot** [comment]
Two potential problems to look at: this is probably floating point error due to the map being located at extreme distances from origin. It could also be due to camera if we are using something like zoom rather than trolley since the back of the frustum will have lower accuracy.

**Comment by aurorahcx** [comment]
I believe this is a precision issue for large coordinate values, the problem disappears after I transform the object's position to be near origin. This is a common rendering problem as rendering pipeline has lower precision support in exchange for performance. 

I am not sure if there's an easy way to render large coordinate values without artifact. I tried https://doc.babylonjs.com/divingDeeper/materials/advanced/logarithmicDepthBuffer but didn't solve the problem.

According to https://github.com/BabylonJS/Babylon.js/issues/4516, a quick work-around could be normalizing all positions. 
If we can process this in map.net.xml, then the problem is solved without code changes. 
If we prefer to keep the current map.net.xml as it is, then we can either normalize the positions from either the SMARTS side or the envision side. It is easier to normalize in the SMARTS side as we only need to normalize the map positions. 
If we leave the normalization process to Envision purely for visualization, then it gets a bit more tedious because we would need to normalize the map mesh positions, traffic actor positions, waypoint positions, driven path positions, bubble positions, etc.

**Comment by Gamenot** [comment]
Steve can help with this.

**Comment by sah-huawei** [comment]
Addressed with PR #673.
