### ISSUE TITLE
NGSIM dataset abnormal replay

### ISSUE THREAD

**Issue by zbzhu99** [huawei-noah/SMARTS#407]
The data replay of the NGSIM data set on SMARTS seems to have some problems:
1. The overall position of the vehicle is offset downwards
2. The front of the vehicle will swing when it first enters the scene
3. The replay speed is obviously too fast

https://user-images.githubusercontent.com/32090492/104401449-2edf4300-558f-11eb-94a1-eee969bd2ae8.mov

Perhaps the way PPUU processes data can be used as a reference.

This is the NSGIM dataset file used by PPUU: http://bit.ly/PPUU-data

The following is some code of PPUU data processing:

https://github.com/Atcold/pytorch-PPUU/blob/2e087d9ef556cf75723ff2c5f5b71c4bb0b358dc/map_i80.py#L18-L41

**Comment by JingfeiPeng** [comment]
Currently there is some mismatch between the vehicle data and map data. Vehicles are off the route when they are initially spawned, causing the the training to be done at first step (as vehicles are already off route). This could also be why the vehicles are offset downwards. It seems either the map data is incorrect or the vehicle position data is incorrect.

**Comment by liamchzh** [comment]
@zbzhu99 Can you share the map.net.xml that you're using. Please upload it in the comment. Thank you.

**Comment by Gamenot** [comment]
@Gamenot @zbzhu99 Reminder to upload the `map.net.xml` file related to the dataset.

**Comment by zbzhu99** [comment]
Apologies for the delayed response, and here is the map file related to the dataset:


[map.net.xml.zip](https://github.com/huawei-noah/SMARTS/files/6003713/map.net.xml.zip)

**Comment by sah-huawei** [comment]
Just from watching the attached video, it appears that the vehicle locations may be "flipped" from top to bottom (i.e., mirrored around the x-axis).  It appears that vehicles are merging from the top down, as opposed from the bottom up.

**Comment by sah-huawei** [comment]
I've finally addressed most of the things in this issue in PR #741, including flipping the coordinate system around the x-axis.  However, the attached `map.net.xml`still doesn't quite match the trajectories in the NGSIM dataset.  

In particular, it has an extra lane at the bottom as compared to:
- the [image of that stretch of highway](https://github.com/Atcold/pytorch-PPUU/blob/master/I-80/cam2.png) from the PPUU repository;
-  the data dictionary ( `trajectory-data-dictionary.htm`) in the [NGSIM dataset from PPUU](http://bit.ly/PPUU-data);
-  Figure 2 [here](https://www.fhwa.dot.gov/publications/research/operations/06137/index.cfm); and
-  the metadata for the lane IDs [here](https://data.transportation.gov/api/views/8ect-6jqj/files/08ab2236-3687-4904-a2b4-b78c7ce42f36?download=true&filename=2-%20I-80%20Metadata%20Documentation.pdf).

In all of these cases, there are only 6 normal lanes and 1 on-ramp.  This appears to be the case in the original PPUU data itself as well.  However, in the attached `map.net.xml`, there are 7 lanes and 1 on-ramp.  The bottom-most lane seems to be incorrect and has shifted the on-ramp down such that merging vehicles do not align with the on-ramp correctly.  

@zbzhu99 Where did you get the `map.net.xml` file you attached?  Could it possibly be associated with another variation of the NGSIM dataset?  If not, maybe we need to update it?

**Comment by sah-huawei** [comment]
Now that PR #741 has been merged into `develop`, the main outstanding things for this issue still are:
1. getting an updated `map.net.xml` from @zbzhu99 to test with; and
2. the heading swing mentioned above.

Re #2, this was improved with PR #741.  Headings are not present in NGSIM and so are inferred from how a vehicle's position changes across a rolling 3-time-step window.  The problem comes now when vehicles are going very slowly (such as in a traffic jam) due to slight FP imprecision in the `x` and `y` positions relative to one another.  PR #741 attempted to smooth this out a bit by preventing heading changes for vehicles going less than ~5 MPH, but there is still a little wiggle for faster (but still slow) vehicles.  

One option is to make the rolling window used to compute the heading bigger.  There are other things we might do too.   But before doing this it would be useful to know what the requirements are... i.e., how important to imitation learning is the vehicle's heading on a particular step?  @zbzhu99, could you please check it out (with PR #741, once you get the new map) and see if it meets your requirements?

**Comment by sah-huawei** [comment]
I've updated `map.net.xml` to remove the extra lane and attached it here.  It may not precisely match i80, but it's close enough that none of the merging vehicles get flagged as being off-road.  There may be another update coming with respect to Issue #742, but this map should work with the scale represented by the `yaml` currently in Issue #732.

[map.net.xml.zip](https://github.com/huawei-noah/SMARTS/files/6347959/map.net.xml.zip)

**Comment by sah-huawei** [comment]
Closing this in lieu of Issue #847.

**Comment by sah-huawei** [comment]
Closed this in lieu of Issue #847.

**Comment by sah-huawei** [comment]
Adding a version of the NGSIM i80 map at 1:1 scale, as well as a  `.yaml` file that can be used to import history data for it.

[ngsim-i80.zip](https://github.com/huawei-noah/SMARTS/files/6489694/ngsim-i80.zip)
