### ISSUE TITLE
Possibility of running Smarts without any graphical output? 

### ISSUE THREAD

**Issue by Sriram94** [huawei-noah/SMARTS#605]
Is it possible to make the simulator run by suppressing all graphical output and related connections necessary for that. Nodes that support GPUs and graphical outputs are limited (if at all) in HPCs, and it would be great if you can make the simulator run without a need for an explicit graphical output.

**Comment by Gamenot** [comment]
@Sriram94 thank you for the question. Yes, it is entirely possible to suppress the graphical output.

If using any of the inbuilt environments is to pass in `headless=True` and `visdom=False`.

https://github.com/huawei-noah/SMARTS/blob/feee8fd8a1f0c10ab2aaf6f12acc8c9cc0f861af/smarts/env/hiway_env.py#L70-L82

If using SMARTS directly it is possible to not render by simply not providing the `envision` or `visdom` parameters.

https://github.com/huawei-noah/SMARTS/blob/feee8fd8a1f0c10ab2aaf6f12acc8c9cc0f861af/smarts/core/smarts.py#L81-L91

**Comment by Gamenot** [comment]
@Sriram94 , I apologise I was about to close the issue but just connected what might be the problem you have. There still needs to be a display, even if a dummy one, in order to use smarts as it is now.

We have a Dockerfile that shows some of the set-up to solve the problem of a missing display:
https://github.com/huawei-noah/SMARTS/blob/feee8fd8a1f0c10ab2aaf6f12acc8c9cc0f861af/Dockerfile#L32-L33

At minimum this means: the following dependencies
```
apt-get install x11-apps xserver-xorg-video-dummy
```

And then there are a few extra steps to set up the "x-server":
https://github.com/huawei-noah/SMARTS/blob/feee8fd8a1f0c10ab2aaf6f12acc8c9cc0f861af/Dockerfile#L45-L49

And then the dummy "x-server" will need to run in the background, this following command will need to be run every time the "x-server" is taken down:
https://github.com/huawei-noah/SMARTS/blob/feee8fd8a1f0c10ab2aaf6f12acc8c9cc0f861af/Dockerfile#L67-L71

**Comment by Sriram94** [comment]
This definitely makes a lot more sense. Thanks for the clarification @Gamenot. My issue was asking if it was possible to look into a version of Smarts without this display. In the meantime I will work with the suggestions you have given me. Thanks.

**Comment by sah-huawei** [comment]
PR #729 may have helped with this.  If you do not have any vehicles with camera-based sensors (that require the display for rendering their observations), you can now run Smarts without a display.  I won't close this yet though, as it hasn't yet been merged into master and released.  I note that we also would still like to remove this final dependency for camera-based sensors as well, eventually, but that will require considerably more work.

**Comment by Adaickalavan** [comment]
For headless Panda3D rendering, consider using `./utils/docker/Dockerfile.headless` in pull request #1016 .
