### ISSUE TITLE
Multiple instances of `RemoteAgentBuffer` will cause `seg fault`

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#719]
## Description
Instantiating multiple instances of `RemoteAgentBuffer` will cause a segmentation fault. This is a problem because it blocks having more than one instance of SMARTS from being instantiated in the same process.

## Context
> I have tested to see that you can have two instances of the `Renderer` in the same thread so I think this PR accomplishes the intention. I still would prefer to see a simple test for this.
> 
> I also understand why there is a rendering lock... I wonder about the implications of it on performance but it is enough that rendering for multiple simulations is possible on the same process.
> 
> In addition, what I have found is that the `RemoteAgentBuffer` currently prevents two instances of SMARTS from existing on the same thread so I am adding that as an issue.

_Originally posted by @Gamenot in https://github.com/huawei-noah/SMARTS/pull/706#issuecomment-810547213_

**Comment by sah-huawei** [comment]
I've confirmed this is the case and is related to the version of the `grpcio` dependency.
Version 1.31.0 causes a segfault in the simple test in PR #745 on this line `grpc.channel_ready_future(self._worker_channel).result(timeout=30)`  in the `RemoteAgent` `__init__` function.
(Using gdb, it can be seen the segfault is caused by a `Flush` in the `grpc` C code.  Probably a threading bug.)

Versions 1.35.0 and 1.37.0 (the latest) don't segfault.

**Comment by sah-huawei** [comment]
@Adaickalavan

**Comment by sah-huawei** [comment]
This is currently the only reason we can't run multiple instance of SMARTS in the same process, and so can't run our tests without `--forked` cf. Issue #743.
