### ISSUE TITLE
Simplify top level of the SMARTS repo

### ISSUE THREAD

**Issue by junluo-huawei** [huawei-noah/SMARTS#776]
There are 35+ items at the top level of the SMARTS repo. Will be nice if we can reduce this down to somewhere between 10 and 20. It'll hopefully be easier for users to navigate the project and understand it structure.

**Comment by sah-huawei** [comment]
A few proposals:
- Move the `./cli/`, `./zoo/` and `./envision/` folders into `./smarts/`.  
    - (`./zoo/` will have to be appropriately combined with `./smarts/zoo/.)
- Make a new `./etc` folder and put the following in it:
    - `setup/`
         - `install_deps.sh`
         - `requirements.txt`
         - `setup.py`
         - `test_pip_packages.sh`
     - `docker/`
         - `Dockerfile`
         - `Dockerfile.minimal`
     - (the stuff in the `./extras/` folder)
     - (the stuff in the `./third_party` folder)
- Make a new `bin/` folder and move the following into it:
    - `header_test.sh`
    - `gen_header.sh`
- Move the stuff in the `./tools/` folder into `./examples/` and/or `./etc/`.
- Move the `./benchmark/` folder down from the top level to somewhere appropriate (not sure where, since I don't really know it's history or rationale).
