### ISSUE TITLE
Update Docker Containers to fix `/dev/input/ No such directory`

### ISSUE THREAD

**Issue by guanjiayi** [huawei-noah/SMARTS#800]
**version:**
v0.4.12 docker
**command:**
`python examples/single_agent.py scenarios/loop`

**error:**
_:device(error): Error adding inotify watch on /dev/input: No such file or directory
:device(error): Error opening directory /dev/input: No such file or directory_

**Comment by Gamenot** [comment]
@guanjiayi Hello, `mkdir -p /dev/input` in the docker container should remove the problem.

The current situation will not cause a problem since SMARTS does not use input handling (keyboard/mouse). However, we will be updating our docker images to touch that directory to remove the cause of the error log.
