### ISSUE TITLE
Circular dependencies when adding type hints

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#859]
So I tried that (with the import as you specified it) but got a weird error on importing due to circular references:
```
Traceback (most recent call last):
  File "/home/steve/Repos/Huawei/SMARTS/examples/observation_collection_for_imitation_learning.py", line 9, in <module>
    from smarts.core.smarts import SMARTS
  File "/home/steve/Repos/Huawei/SMARTS/smarts/core/smarts.py", line 42, in <module>
    from .agent_manager import AgentManager
  File "/home/steve/Repos/Huawei/SMARTS/smarts/core/agent_manager.py", line 31, in <module>
    from smarts.core.smarts import SMARTS
ImportError: cannot import name 'SMARTS' from 'smarts.core.smarts' (/home/steve/Repos/Huawei/SMARTS/smarts/core/smarts.py)
```

It's probably possible to fix this, but given that I'm already a bit predisposed against specifying `SMARTS` here as the type, I'm going to go ahead and pass on this one.

_Originally posted by @sah-huawei in https://github.com/huawei-noah/SMARTS/pull/827#discussion_r632888483_

**Comment by sah-huawei** [comment]
Changed tag from "bug" to "enhancement".  This isn't a bug.  It only becomes a problem if we want to add type hits because these often necessitate adding more imports (to import the type for the hint) which can then lead to circular import dependencies.  Things work fine though without the type hints.
