### ISSUE TITLE
how to use PPO benchmark in single agent case

### ISSUE THREAD

**Issue by Dikshuy** [huawei-noah/SMARTS#881]
** High-Level Description**
How can I use the PPO benchmark, so that I can provide actions to ego agents using this policy?

**Desired SMARTS version**
0.4.12

**Operating System**
ubuntu 18.04

**Problems**
I want the ego agents to take actions using the PPO policy, provided by SMARTS. I don't know whether this is already implemented or not. I have seen that there are some YAML files in the benchmark directory, so I hope it's already implemented.  I am referring to these YAML files that are present in the benchmark directory. 
[https://github.com/huawei-noah/SMARTS/tree/master/benchmark/agents/ppo](https://github.com/huawei-noah/SMARTS/tree/master/benchmark/agents/ppo)
@Gamenot

**Comment by Leoluo0320** [comment]
Hi Dikshuy. I have the similar problem. Also, I wonder if I run the agent under examples directory, they seem not have any learning process?

**Comment by Adaickalavan** [comment]
@Dikshuy @LeoLuo0320 Please refer to the unprotected left-turn intersection [example](https://github.com/huawei-noah/SMARTS/tree/master/examples/rl/intersection) which shows how StableBaselines3 PPO may be used to develop a reinforcement learning agent

**Comment by Adaickalavan** [comment]
@Dikshuy @LeoLuo0320 

Please refer to the unprotected left-turn intersection at [SMARTS/examples/rl/intersection](https://github.com/huawei-noah/SMARTS/tree/53ff4131d1649ddf05156219d3ab8bee1aa9c4f2/examples/rl/intersection) which shows how StableBaselines3 PPO algorithm may be used to develop a reinforcement learning agent to turn left at an unprotected intersection.

We hope the above addresses your question and thus this issue is being closed. Please feel free to reopen this issue if your problem persists or open a new issue for other questions.
