### ISSUE TITLE
benchmark/agents/common  function cal_lane_its_info seems to have errors

### ISSUE THREAD

**Issue by feidieufo** [huawei-noah/SMARTS#90]
Even if there are many cars in intersections, the flag **intersection_distance** and **closest_its_nv_rel_speed**  is no different
I think line 624  has errors,         
```
line_heading = (
                (np.arctan2(nv_to_ego_vec[:, 1], nv_to_ego_vec[:, 0]) * 180 / np.pi)
                - 90
            ) % 360
 nv_to_line_heading = (nv_heading - line_heading) % 360
 ego_to_line_heading = (ego_heading - line_heading) % 360
```
I replace -90 to +90, the flag **intersection_distance** and **closest_its_nv_rel_speed** can have a effect
I think there may be other angle calculation errors in this file

**Comment by Gamenot** [comment]
Taking a quick look, it seems like the `heading_to_degree` and `heading_to_vec` conversions have an errors converting from north facing heading to east facing degrees. Counter clockwise rotation should have the conversions subtracting 0.5 pi.

**Comment by Hyperion-shuo** [comment]
> Taking a quick look, it seems like the `heading_to_degree` and `heading_to_vec` conversions have an errors converting from north facing heading to east facing degrees/radians. Counter-clockwise rotation should have the conversions subtracting 0.5 pi.
> 
> There is someone looking into it.

In line 68, it says heading_to_degree function takes 0 as up direction , but actually 0 means down direction.See code and picture blow:

    def heading_to_degree(heading):

    ### +y = 0 rad. Note the 0 means up direction ###

    return np.degrees((heading + math.pi) % (2 * math.pi))

<img width="412" alt="WechatIMG1251" src="https://user-images.githubusercontent.com/55169296/97670865-1c8e5680-1ac2-11eb-9320-15b138b3a49c.png">
<img width="239" alt="WechatIMG1252" src="https://user-images.githubusercontent.com/55169296/97670874-20ba7400-1ac2-11eb-839f-23572c3e8d96.png">

So line 301 minus 90 degree to convert **heading_to_vec** from east to north because it thinks **heading_to_degree** is north facing。Actually heading_to_degree is south facing, is should add 90.

**Comment by mg2015started** [comment]
@feidieufo @Gamenot @Hyperion-shuo yes, this is a bug.

**Comment by feidieufo** [comment]
@mg2015started  I found another problem,in common.py,when I use cruising.yaml, in get_reward_adapter function，
```
    def cruising(last_env_obs, env_obs, env_reward):
        global lane_crash_flag
        global intersection_crash_flag
```
lane_crash_flag and intersection_crash_flag is always false
```
         # if to collide in 3s, make it slow down
         if ttc < 2 or ego_closest_its_nv_distance < 6:
             intersection_crash_flag = True
```
 intersection_crash_flag has been modified before
but in the reward function the intersection_crash_flag is still false

**Comment by mg2015started** [comment]
@feidieufo
