### ISSUE TITLE
Error occurs when running run.py under benchmark directory

### ISSUE THREAD

**Issue by Leoluo0320** [huawei-noah/SMARTS#905]
**High Level Description**
Trying to run "run.py" under the benchmark directory. Some errors occurred during the process but do not stop the process. Not sure if they matter.

**Desired SMARTS version**
0.4.16

**Operating System**
ubuntu 16.04

**Problems**
command:
python run.py scenarios/intersections/4lane -f agents/ppo/baseline-lane-control.yaml

During the process of running "run.py" under the benchmark directory, "traci.exceptions.FatalTraCIError: connection closed by SUMO" and "AttributeError: 'Connection' object has no attribute '_socket'" occurs. The training process can still continue. Checkpoints generated under the log/results/run/4lane-4 directory.

error.txt:
[error.txt](https://github.com/huawei-noah/SMARTS/files/6588392/error.txt)

**Comment by Gamenot** [comment]
@Leoluo0320 Hello, yes, our apologies for this. This is a low frequency error caused by SUMO which we have [reported the error to them](https://github.com/eclipse/sumo/issues/8381) and mitigated the impact of the error already so it should cause minimal disruption to SMARTS. 

We generally just accept the infrequent error and abort that episode since caching SUMO's state to restart SUMO would be both inefficient and fragile.

**Comment by Leoluo0320** [comment]
Got it! Thank you for your reply.
