### ISSUE TITLE
ULTRA: Error occurs when training and evaluating baseline agent

### ISSUE THREAD

**Issue by Leoluo0320** [huawei-noah/SMARTS#923]
**High Level Description**
I am trying to train the baseline agent of ULTRA. "TypeError: 'NoneType' object is not callable" occurs when the trainning is finished. Model directory is generated under the logs directory. But when evaluating the model, "TypeError: expected str, bytes or os.PathLike object, not NoneType" occurs, I think it is related to the error occurs when training. (Also, the command for evaluating does not need --policy argument)

**Desired SMARTS version**
0.4.16

**Operating System**
ubuntu 16.04

**Problems**
Command used:
training:
python ultra/train.py --task 1 --level easy --episodes 10 --eval-episodes 5 --eval-rate 100 --policy dqn

evaluating:
python ultra/evaluate.py --task 1 --level easy --episodes 5 --models logs/<experiment_dir>/models

**Comment by christianjans** [comment]
Hi @Leoluo0320, thanks for submitting the issue. Yes, I took a look at the existing documentation for evaluation and it is out of date with our current ULTRA version. I will work on updating it.

When training is complete, we also get that `TypeError: 'NoneType' is not callable` error. This is due to the GRPC dependency's version in SMARTS. See issue #735 for more context. The SMARTS team has since upgraded the GRPC dependency, however, we do not use that SMARTS version with the upgraded GRPC dependency yet in ULTRA. In the meantime, the error is nothing to worry about and training should run fine and produce an experiment directory (like you have experienced).

The error encountered in evaluation is actually a bit different. We had recently changed the command line arguments for the evaluation script, so instead, try running:
```bash
(.venv) $ python ultra/evaluate.py --task 1 --level easy --episodes 5 --models logs/<experiment_dir>/models/000/ --experiment-dir logs/<experiment_dir>/
```

Let us know how this goes, and please continue to ask if you have any more questions or run into any more problems!

**Comment by christianjans** [comment]
See #925 for updated documentation.

**Comment by Leoluo0320** [comment]
Thank you for you update. I will try it and let you know if there is any further problem.

**Comment by Leoluo0320** [comment]
Hi @christianjans, I checked the update documentation and tried myself. The argument "--models" needs logs/<timestamped_experiment_name>/models/<model_number>, as you mentioned in the first post. If no model_number is given, "StopIteration Error" will occur in evaluate.py.

**Comment by christianjans** [comment]
Ahh thank you, yes I forgot to add that in the docs, thanks!

**Comment by christianjans** [comment]
Closing as the issue seems to be resolved. Feel free to reopen or create a new issue if there are any more problems encountered.
