### ISSUE TITLE
potential for imitation learning

### ISSUE THREAD

**Issue by m485liuw** [huawei-noah/SMARTS#973]
**High Level Description**
[Describe what your goal is]
I saw there's observation_collection_for_immitation_learning.py under examples. It seems to be incomplete and only includes observation. For imitation learning, we need actions as well. I'm wondering is it possible to have action collected under each observation?

**Comment by sah-huawei** [comment]
Hi @m485liuw.  Thanks for your question!  The TLDR to your question is "it's not there yet, but we will try to add something in a future version."  I've added Issue #979 to track this.  Please feel free to add to / expand upon it.

That script (`observation_collection...`) was created for a specific experiment, along with another one (`history_vehicles_replacement_for_imitation_learning.py`).  Together, these were used with traffic history datasets (for example, NGSIM and INTERACTION) in order to produce data on how vehicles interact and behave in merging situations.  In those datasets, we're given information on how real vehicles moved (their trajectories through time), but not information about what controls (actions) were being applied by their real drivers. 

The `observation_collection...` script was basically just a way to "convert" those datasets into a form that could be used to train imitation learning agents (i.e., convert the trajectories into SMARTS' "observations") such that the models could then be further refined and tested in the SMARTS simulator.  The other script then (`history_vehicles_replacement...`) was used for that by picking one or more vehicles at a time and controlling them with the IL models, allowing the IL agents to "drive amongst real traffic". 

In regards to your specific question, if the goal of IL is to learn to imitate a _human_ driver, then the dataset should probably contain information about the actions being taken by actual humans.  It's sort of a chicken-egg problem because if you can simulate that in a realistic-enough way to generate data _without_ humans in the loop, you have probably already solved most of the problem.  However, it might still be useful to use SMARTS to bootstrap IL models by providing the actions taken by simulated drivers, even if these are not quite human.  

To that end, we will consider adding `throttle` and `brake` fields to our `EgoVehicleObservation` class.  (Note:  we already have `steering` there.)  And please let us know if there is any other information you think might be useful to add there too.

We know we have only scratched the surface of using SMARTS for Imitation Learning so far.  In the coming year, we are planning to build out more features to support IL research.  Feedback from the IL community is very important to us, so thank you again for reaching out, and please do let us know specifics going forward.
