### ISSUE TITLE
Camera images are blank in the first few steps when a new agent is created inside bubble

### ISSUE THREAD

**Issue by Nickniyihan** [huawei-noah/SMARTS#99]
Around 10 steps upon  the creation of boid agent, that is, 10 steps after a vehicle is hijacked by bubble and policy.act(obs) has been requested 10 times, with obs.ogm and obs.drivable_area fed to act() being blank!

**Comment by aurorahcx** [comment]
The social agent is already created in _airlock_social_vehicle_with_social_agent() in the bubble manager, causing observe() to ask for grid maps while step() hasn't been called to update camera position, resulting in blank images. 
step() is not triggered because hijacked vehicle is not yet added to agent_vehicle_ids in vehicle index during airlock, until later _hijack_social_vehicle_wtih_social_agent() is called in bubble manager to swtich the control to agent. 

Waiting for feedback from @JVillella to check if this is the intended behavior of the bubble manager design.

**Comment by Nickniyihan** [comment]
@aurorahcx Thanks for the thorough investigation! My question is that will this cause the agent to miss several (more than one) steps of camera images?

**Comment by aurorahcx** [comment]
There is no frame mismatch between grid maps and other observation information. Currently the hijacked vehicle is providing blank images during airlock when it first enters the bubble, as it is in the process of being controlled by an agent. 

I guess what we would like to confirm is, whether it is ok for the hijacked vehicle to have blank grid maps during airlock.
